- src: https://github.com/dockpack/base_common.git
  name: dockpack.base_common

- src: https://github.com/dockpack/base_epel.git
  name: dockpack.base_epel

- src: https://github.com/dockpack/base_cplusplus.git
  name: dockpack.base_cplusplus
