---

# this could be refactored for normal user mode
- name: 'run redhat tasks.yml'
  when: ansible_os_family == 'RedHat'
  include_tasks: RedHat.yml

- name: 'run redhat tasks.yml'
  when: ansible_os_family == 'Debian'
  include_tasks: Debian.yml

- name: 'ensure CPAN config exists'
  become: true
  file:
    path: '/root/.cpan/CPAN/'
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - perl
    - perl_config

- name: 'install CPAN configuration'
  become: true
  template:
    src: 'MyConfig.pm'
    dest: '/root/.cpan/CPAN/'
    mode: 0600
  tags:
    - perl
    - perl_config

- name: 'install App::cpanminus'
  become: true
  copy:
    src: 'cpanminus.pl'
    dest: '/root/cpanminus.pl'
    mode: 0700
  tags:
    - perl
    - perl_config

- name: 'query for CPANM'
  become: false
  command: perl -MApp::cpanminus -e exit;
  no_log: false
  register: cpanm_present
  failed_when: not cpanm_present.rc in [0, 2]
  changed_when: false
  tags:
    - skip_ansible_lint

- name: 'installing CPANM'
  become: true
  when: cpanm_present.rc != 0
  shell: >
    set -o pipefail; \
    cat /root/cpanminus.pl | perl - App::cpanminus
  args:
    executable: /bin/bash
  tags:
    - perl

# Perl modules with Ansible
- name: 'install optional modules'
  become: true
  command: /usr/local/bin/cpanm "{{ item.module }}"
  args:
    creates: "{{ item.creates }}"
  with_items: "{{ perl_modules }}"
  tags:
    - perl
    - perl_modules
    - skip_ansible_lint
