---

# this could be refactored for normal user mode
- name: 'install required RPMs for Perl development'
  become: yes
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ perl_rpms }}"
  tags:
    - perl
    - perl_rpms

- name: 'apt install packages for Perl development'
  when: ansible_os_family == 'Debian'
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items: "{{ perl_apts }}"
  tags:
    - perl
    - perl_apts

- name: 'ensure CPAN config exists'
  become: yes
  file:
    path: '/root/.cpan/CPAN/'
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - perl
    - perl_config

- name: 'install CPAN configuration'
  become: yes
  template:
    src: 'MyConfig.pm'
    dest: '/root/.cpan/CPAN/'
  tags:
    - perl
    - perl_config

- name: 'install App::cpanminus'
  become: yes
  copy:
    src: 'cpanminus.pl'
    dest: '/root/cpanminus.pl'
  tags:
    - perl
    - perl_config

# Dirty yes.
- name: 'query for CPANM'
  become: no
  command: perl -MApp::cpanminus -e exit;
  ignore_errors: yes
  no_log: yes
  register: cpanm_present
  changed_when: no
  tags:
    - skip_ansible_lint

- name: 'installing CPANM'
  become: yes
  when: cpanm_present.rc != 0
  shell: 'cat /root/cpanminus.pl | perl - App::cpanminus'
  tags:
    - perl

# Perl modules with Ansible
- name: 'install optional modules'
  become: yes
  command: /usr/local/bin/cpanm "{{ item.module }}"
  args:
    creates: "{{ item.creates }}"
  with_items: "{{ perl_modules }}"
  tags:
    - perl
    - perl_modules
    - skip_ansible_lint
